# Generated by Django 5.0.3 on 2024-04-06 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_is_activate_user_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_active',
            new_name='is_activate',
        ),
    ]
